#!/bin/sh

if ! type "gpio" > /dev/null
then
	echo "WiringPi was not found!"
	echo "Please run the build script to install your OPL2 Audio Board first."
	echo ""
	exit
fi

PIN_LATCH=$(gpio readall | awk -F\| '{if ($3==1) print $7} {if ($13==1) print $9}')
PIN_A0=$(gpio readall | awk -F\| '{if ($3==4) print $7} {if ($13==4) print $9}')
PIN_RESET=$(gpio readall | awk -F\| '{if ($3==5) print $7} {if ($13==5) print $9}')
PIN_DATA=$(gpio readall | awk -F\| '{gsub(/ /, "", $4) ; if ($4=="MOSI") print $7} {gsub(/ /, "", $12) ; if ($12=="MOSI") print $9}')
PIN_SHIFT=$(gpio readall | awk -F\| '{gsub(/ /, "", $4) ; if ($4=="SCLK") print $7} {gsub(/ /, "", $12) ; if ($12=="SCLK") print $9}')

echo ""
echo "Connect the OPL2 Audio Board to your Raspberry Pi like this:"
echo ""
echo "+------------+------+"
echo "| OPL2 Board | GPIO |\tGPIO header orientation:"
echo "+------------+------+"
echo "|      Reset |\033[1m $PIN_RESET \033[0m|\t                     \033[1;32m|\033[0m"
echo "|      Shift |\033[1m $PIN_SHIFT \033[0m|\t        ...\033[1m 5 3 1    \033[1;32m|\033[0m"
echo "|      Latch |\033[1m $PIN_LATCH \033[0m|\t       -----------+  \033[1;32m|\033[0m"
echo "|       Data |\033[1m $PIN_DATA \033[0m|\t      \033[1;33m  o o o o o \033[0m|  \033[1;32m|\033[0m"
echo "|         A0 |\033[1m $PIN_A0 \033[0m|\t     \033[1;33m o o o o o o \033[0m|  \033[1;32m|\033[0m"
echo "|        GND |\033[1m  6   \033[0m|\t     -------------+  \033[1;32m|\033[0m"
echo "|        +5v |\033[1m  2   \033[0m|\t        ...\033[1m 6 4 2    \033[1;32m|\033[0m  <-- Raspberry Pi"
echo "+------------+------+\t  \033[1;32m------------------'\033[0m       board edge"
echo ""
