#!/bin/sh

if ! type "gpio" > /dev/null
then
	echo "WiringPi was not found!"
	echo "Please run the build script to install the OPL2 library first."
	echo ""
	exit
fi

echo ""
echo "Connect the OPL3 Duo! to your Raspberry Pi like this:"
echo ""
echo "+-----------+------+"
echo "| OPL3 Duo! | GPIO |"
echo "+-----------+------+"
echo "|     +3.3v |\033[1m   1  \033[0m|\t GPIO header connection:"
echo "|       GND |\033[1m   6  \033[0m|"
echo "|        A2 |\033[1m  22  \033[0m|\t                     \033[1;32m|\033[0m"
echo "|        A1 |\033[1m  18  \033[0m|\t        ...\033[1m 5 3 1    \033[1;32m|\033[0m"
echo "|        A0 |\033[1m  16  \033[0m|\t       -----------+  \033[1;32m|\033[0m"
echo "|      MOSI |\033[1m  19  \033[0m|\t      \033[1;33m  o o o o o \033[0m|  \033[1;32m|\033[0m"
echo "|       SCK |\033[1m  23  \033[0m|\t     \033[1;33m o o o o o o \033[0m|  \033[1;32m|\033[0m"
echo "|       /WR |\033[1m  15  \033[0m|\t     -------------+  \033[1;32m|\033[0m"
echo "|       /IC |\033[1m  13  \033[0m|\t        ...\033[1m 6 4 2    \033[1;32m|\033[0m  <-- Raspberry Pi"
echo "+-----------+------+\t  \033[1;32m------------------'\033[0m       board edge"
echo ""
